# -*- coding: utf-8 -*-
"""`oser doctor` — inspect a project's EFFECTIVE control plane and report drift.

Severity: critical (wrong truth is being served, or a dangerous default) · warning (drift that will bite)
· info (context). Exit code: 2 when any critical, 1 when any warning, else 0.

Every check is either GENERIC (works on any project) or DECLARED (driven by data the project put in its
manifest, e.g. stale markers, Firebase targets). The report labels each finding with its basis so a clean
score cannot hide behind undeclared checks.
"""
import glob
import json
import os
import re

from . import render
from .engine import CONTROL_PLANE_DOC, SETTINGS, detect_legacy
from . import ledger
from .manifest import (LOCK, MANIFEST, build_state, get, legacy_keys, load, mode_spec, ref_exists,
                       resolve_authority, root_model)
from .transcripts import observed_models
from .util import (OSER_HOME, claude_home, git, load_catalog, load_json, match_any, model_generation, plugin_version,
                   read_text, rel, sha, MODEL_RE)

SEV_ORDER = {"critical": 0, "warning": 1, "info": 2}
STATE_MAX_BYTES = 15 * 1024   # measured rule (references/3-luat-tiet-kiem.md, luật 9): 157 KB state ≈ 60k tokens/turn
BRANCH_RE = re.compile(r"\bbranch\W{0,6}`([A-Za-z0-9._/-]+)`", re.I)
PHASE_CLAIM_RE = re.compile(r"current phase", re.I)
FAMILY_CLAIM_RE = re.compile(r"\b(fable|opus|sonnet|haiku)\s+\d", re.I)   # "Opus 5" = the seat claims a tier


class Report:
    def __init__(self):
        self.findings = []
        self.facts = {}

    def add(self, sev, cid, msg, path=None, basis="generic"):
        self.findings.append({"severity": sev, "id": cid, "message": msg, "path": path, "basis": basis})

    def counts(self):
        c = {"critical": 0, "warning": 0, "info": 0}
        for f in self.findings:
            c[f["severity"]] += 1
        return c


def _current_files(root, m):
    files = ["CLAUDE.md"]
    if m:
        files.append(m["workspace"]["state_file"])
        files += (m.get("control_plane") or {}).get("current") or []
    out = []
    for f in files:
        if f not in out and os.path.isfile(os.path.join(root, f)):
            out.append(f)
    return out


def run(root, manifest_override=None):
    r = Report()
    root = os.path.abspath(root)
    version = plugin_version()
    r.facts.update({"project": root, "oser_version": version, "oser_home": OSER_HOME})
    m, errors = load(root, manifest_override)
    if m is None:
        r.add("critical", "OSR-001", "no OSER manifest (%s): project is not under NNC OSER" % MANIFEST, MANIFEST)
    for e in errors if m is not None else []:
        r.add("critical", "OSR-001", "manifest: " + e, MANIFEST)
    valid = m is not None and not errors
    if valid:
        r.facts.update({"mode": m["mode"], "phase": m["phase"]["label"]})
        _lock(r, root, m, version, manifest_override)
        _authority(r, root, m)
        _phase(r, root, m)
        _mode(r, root, m)
        _workspace(r, root, m)
        _generated(r, root, m, version)
        _firebase(r, root, m)
        _build(r, root, m)
        _ledger(r, root, m)
    _org_model(r, root, m)
    _branch_pointers(r, root, m if valid else None)
    _models(r, root, m if valid else None)
    _legacy(r, root, m if valid else None)
    _plugin(r, root, version)
    _git(r, root, (get(m, "git.main") if valid else None) or "main")
    r.findings.sort(key=lambda f: (SEV_ORDER[f["severity"]], f["id"], f["path"] or ""))
    return r


# ------------------------------------------------------------------------------------------- checks

def _lock(r, root, m, version, manifest_override):
    lock = load_json(os.path.join(root, LOCK))
    if not lock:
        r.add("critical", "OSR-002", "no %s: no provenance — nothing proves which OSER version/mode generated "
              "this control plane (run oser migrate / install)" % LOCK, LOCK)
        return
    lv = lock.get("oser_version")
    r.facts["lock_version"] = lv
    if lv != version:
        newer = _vt(version) > _vt(lv or "0")
        r.add("warning" if newer else "critical", "OSR-002",
              "project generated by OSER %s, running %s — %s" % (lv, version, "run oser update" if newer
                                                                   else "running OSER is OLDER than the project"), LOCK)
    manifest_text = read_text(manifest_override or os.path.join(root, MANIFEST))
    if lock.get("manifest_sha256") != sha(manifest_text):
        r.add("warning", "OSR-002", "manifest changed since last `oser update` — generated files may be stale", MANIFEST)
    if lock.get("mode") != m["mode"]:
        r.add("critical", "OSR-002", "lock mode %r disagrees with manifest mode %r" % (lock.get("mode"), m["mode"]), LOCK)


def _vt(v):
    try:
        return tuple(int(x) for x in str(v).split("."))
    except ValueError:
        return (0,)


def _authority(r, root, m):
    a = m["authority"]
    auth = resolve_authority(root, m)
    r.facts["authority"] = "%s @ %s -> %s" % (a["repo"], a["ref"], a["entry"])
    if not auth:
        r.add("warning", "OSR-010", "authority clone of %s not found locally (local_path_hints / NNC_OSER_AUTHORITY_PATH) "
              "— authority pointer cannot be verified" % a["repo"], MANIFEST)
        return
    r.facts["authority_local"] = auth
    ref = ref_exists(auth, a["ref"])
    if not ref:
        r.add("critical", "OSR-010", "authority ref %r does not exist in %s" % (a["ref"], a["repo"]), MANIFEST)
        return
    if git(auth, "cat-file", "-e", "%s:%s" % (ref, a["entry"]))[0] != 0:
        r.add("critical", "OSR-010", "authority entry %s missing at %s" % (a["entry"], a["ref"]), MANIFEST)
    base = a.get("baseline")
    if base:
        if git(auth, "cat-file", "-t", base)[1] != "commit":
            r.add("critical", "OSR-010", "authority baseline %s is not a commit in the local clone" % base, MANIFEST)
        elif git(auth, "merge-base", "--is-ancestor", base, ref)[0] != 0:
            r.add("warning", "OSR-010", "authority baseline %s is not in %s history" % (base, a["ref"]), MANIFEST)
        else:
            n = git(auth, "rev-list", "--count", "%s..%s" % (base, ref))[1]
            if n and n != "0":
                r.add("info", "OSR-010", "authority %s advanced %s commit(s) beyond baseline %s — review the entry file"
                      % (a["ref"], n, base), MANIFEST)


def _branch_pointers(r, root, m):
    auth = resolve_authority(root, m) if m else None
    for f in _current_files(root, m):
        text = read_text(os.path.join(root, f)) or ""
        for tok in sorted(set(BRANCH_RE.findall(text))):
            live = git(root, "rev-parse", "--verify", "--quiet", "refs/remotes/origin/" + tok)[0] == 0 or \
                git(root, "rev-parse", "--verify", "--quiet", "refs/heads/" + tok)[0] == 0 or \
                (auth is not None and ref_exists(auth, tok))
            if not live and (auth is not None or "/" in tok):
                r.add("critical", "OSR-011", "points to branch `%s`, which exists in neither this repo nor the "
                      "authority clone" % tok, f)


def _phase(r, root, m):
    label = m["phase"]["label"]
    state = m["workspace"]["state_file"]
    text = read_text(os.path.join(root, state))
    if text is None:
        r.add("critical", "OSR-020", "workspace state file missing", state)
    elif label not in "\n".join(text.split("\n")[:40]):
        r.add("critical", "OSR-020", "workspace state does not declare the current phase %r in its head" % label, state)
    block = render.extract_block(read_text(os.path.join(root, "CLAUDE.md")) or "")
    if block is None:
        r.add("critical", "OSR-020", "CLAUDE.md has no OSER status block — sessions read no declared phase", "CLAUDE.md")
    elif render.get_block_phase(block) != label:
        r.add("critical", "OSR-020", "CLAUDE.md block phase %r disagrees with manifest %r"
              % (render.get_block_phase(block), label), "CLAUDE.md")
    markers = (m.get("control_plane") or {}).get("stale_markers") or []
    for f in _current_files(root, m):
        full = read_text(os.path.join(root, f)) or ""
        body = full.replace(render.extract_block(full) or "\0", "")
        lines = body.split("\n")
        for i, line in enumerate(lines, 1):
            if PHASE_CLAIM_RE.search(line) and label.lower() not in line.lower():
                r.add("warning", "OSR-021", "line %d claims a current phase other than %r: %s" % (i, label, line.strip()[:110]), f)
            for mk in markers:
                hit = re.search(mk["pattern"], line) if mk.get("regex") else (mk["pattern"] in line)
                if hit:
                    r.add("warning", "OSR-021", "line %d: stale marker %r — %s" % (i, mk["pattern"], mk.get("why", "")), f,
                          basis="declared")


def _models(r, root, m):
    obs = observed_models(root)
    expected = root_model(m) if m else "(no manifest)"
    configured = {}
    for label, p in (("project", os.path.join(root, SETTINGS)), ("project-local", os.path.join(root, ".claude", "settings.local.json")),
                     ("user", os.path.join(claude_home(), "settings.json"))):
        try:
            s = load_json(p) or {}
        except ValueError:
            s = {}
        if s.get("model"):
            configured[label] = s["model"]
    observed = obs["root_last"]
    r.facts["root_model"] = {"expected": expected, "configured": configured or "(none)",
                             "observed": ("%s (session %s, %s)" % (observed[0], observed[2], observed[1][:16])) if observed else "(no transcript)"}
    r.facts["observed_models"] = {"root": obs["root"], "subagent": obs["sub"]}
    if observed is None:
        r.add("info", "OSR-030", "no transcript for this project path — observed ROOT model unknown")
    fam = get(m, "operating_model.root.expected_family") if m else None
    if fam and observed and (model_generation(observed[0]) or ("?",))[0] != fam:
        r.add("warning", "OSR-030", "Root expected family %s, observed %s" % (fam, observed[0]))
    pin = configured.get("project-local") or configured.get("project")
    if expected == "inherit" and pin:
        extra = ""
        if observed and observed[0] != pin:
            extra = " — and the observed ROOT model is %s, so the pin is not what controls the session" % observed[0]
        r.add("warning", "OSR-030", "ROOT model pinned to %s while policy is inherit%s" % (pin, extra), SETTINGS)
    elif m and expected != "inherit" and observed and observed[0] != expected:
        r.add("warning", "OSR-030", "ROOT model expected %s, observed %s" % (expected, observed[0]), SETTINGS)
    newest = {}
    for mid in obs["all"]:
        g = model_generation(mid)
        if g and (g[0] not in newest or g[1] > newest[g[0]][1]):
            newest[g[0]] = (mid, g[1])
    targets = _current_files(root, m) + [rel(root, f) for f in glob.glob(os.path.join(root, ".claude", "agents", "*.md"))]
    targets += [rel(root, f) for f in glob.glob(os.path.join(root, ".claude", "settings*.json"))]
    targets += [x["path"] for x in detect_legacy(root, m)]
    if m:
        targets.append(MANIFEST)
    for f in sorted(set(targets)):
        text = read_text(os.path.join(root, f)) or ""
        stale = set()
        for line in text.split("\n"):
            for mt in MODEL_RE.finditer(line):
                g = model_generation(mt.group(0))
                # a line that also names the newer generation is a comparison/record, not a stale setting
                if g and g[0] in newest and g[1] < newest[g[0]][1] and newest[g[0]][0] not in line:
                    stale.add("%s (observed newer: %s)" % (mt.group(0), newest[g[0]][0]))
        if stale:
            r.add("warning", "OSR-031", "older model generation(s) than observed on this machine: " + "; ".join(sorted(stale)), f)
    for f in glob.glob(os.path.join(root, ".claude", "agents", "*.md")):
        text = read_text(f) or ""
        pin_m = re.search(r"^model:\s*(\S+)", text, re.M)
        desc = re.search(r"^description:\s*(.+)$", text, re.M)
        if pin_m and desc:
            fam = (model_generation(pin_m.group(1)) or (pin_m.group(1).lower(),))[0]
            said = set(w.lower() for w in FAMILY_CLAIM_RE.findall(desc.group(1)))
            if said and fam not in said:
                r.add("warning", "OSR-031", "description names %s but the seat is pinned to %s"
                      % ("/".join(sorted(said)), pin_m.group(1)), rel(root, f))


def _mode(r, root, m):
    spec = mode_spec(m)
    agents = glob.glob(os.path.join(root, ".claude", "agents", "*.md"))
    if agents and spec["subagents"] == "forbidden":
        r.add("critical", "OSR-040", "%d agent definition(s) registered in .claude/agents while mode %r forbids subagents"
              % (len(agents), m["mode"]), ".claude/agents/")
    try:
        s = load_json(os.path.join(root, SETTINGS)) or {}
    except ValueError:
        s = {}
    missing = [d for d in render.managed_settings(m)["deny"] if d not in ((s.get("permissions") or {}).get("deny") or [])]
    if missing:
        r.add("warning", "OSR-040", "mode %r is not enforced: settings.json does not deny %s" % (m["mode"], ", ".join(missing)), SETTINGS)


def _legacy(r, root, m):
    what = {"doi-bac": "model-profile switching", "do-quota": "quota measurement", "bac-dang-dung": "model state"}
    for x in detect_legacy(root, m):
        if x["key"] in what:
            r.add("critical", "OSR-050", "second owner of %s: legacy %s (%s) alongside the plugin implementation"
                  % (what[x["key"]], "generated file" if x["state"] == "generated" else "copy", x["state"]), x["path"])
        else:
            r.add("critical", "OSR-100", "legacy organisation model still in the current tree (%s) — two operating models "
                  "compete; `oser migrate` retires it (git keeps history)" % x["key"], x["path"])


FIXED_ROLE_RE = re.compile(r"\b(worker|mechanical|lead|audit|thợ|cơ khí|tech lead)\b[^\n|]{0,6}(=|→|:)\s*`?(claude-)?(sonnet|haiku|opus|fable)", re.I)


def _org_model(r, root, m):
    """OSR-100 — exactly one current operating model: no fixed model-per-role config, no 1.x roster as current."""
    for k in (legacy_keys(m) if m else []):
        r.add("critical", "OSR-100", "manifest keeps 2.0 fixed model/role configuration %r — retired" % k, MANIFEST)
    cat = load_catalog("legacy-v1.json")
    roster = cat["v1_roster"]
    seat_re = re.compile(r"`(%s)`" % "|".join(re.escape(x) for x in roster))
    for f in _current_files(root, m if m and not legacy_keys(m) else None):
        text = read_text(os.path.join(root, f)) or ""
        body = text.replace(render.extract_block(text) or "\0", "")
        seats = sorted(set(seat_re.findall(body)))
        if seats:
            r.add("warning", "OSR-100", "current file names 1.x seats as if current: %s" % ", ".join(seats), f)
        for loc in (cat["v2_inactive_dir"], cat["v1_team_doc"]):
            if loc in body:
                r.add("warning", "OSR-100", "current file points at a retired roster location %s" % loc, f)
        if FIXED_ROLE_RE.search(body):
            r.add("warning", "OSR-100", "current file maps a role to a fixed model (%s) — model is per packet"
                  % FIXED_ROLE_RE.search(body).group(0).strip(), f)


def _build(r, root, m):
    st = build_state(m)
    r.facts["build"] = st
    if m["mode"] == "build" and st != "admitted":
        r.add("critical", "OSR-101", "mode build without admission", MANIFEST)
    if st == "configured_not_admitted":
        r.add("info", "OSR-101", "BUILD configured, NOT admitted — no governor/worker may run", MANIFEST)
    if m["mode"] == "setup" and st == "admitted":
        r.add("warning", "OSR-101", "build.admission=admitted but mode is still setup", MANIFEST)


def _ledger(r, root, m):
    recs = ledger.read(root)
    if not recs:
        return
    st = ledger.fold(recs, m)
    r.facts["ledger"] = {"waves": len(st["waves"]), "packets": len(st["packets"])}
    for e in st["errors"][:20]:
        r.add("critical", "OSR-102", "ledger: " + e, ledger.path(root).replace(root, "").lstrip("\\/"))
    for n, ev in recs:
        if ev.get("event") == "decision" and ev.get("zone") in ("GREEN", "AMBER") and ev.get("escalated_to_founder"):
            r.add("critical", "OSR-103", "line %d: %s engineering decision %s escalated to Founder — sovereignty boundary: "
                  "Founder resolves only RED" % (n, ev.get("zone"), ev.get("decisionId")))
    r.facts["decisions"] = {z: sum(1 for d in st["decisions"] if d.get("zone") == z) for z in ("GREEN", "AMBER", "RED")}
    for pid, p in st["packets"].items():
        if not (p["open"].get("machine_first") or {}).get("considered"):
            r.add("warning", "OSR-102", "packet %s opened without machine-first consideration" % pid)


def _workspace(r, root, m):
    ws = m["workspace"]
    state = os.path.join(root, ws["state_file"])
    limit = ws.get("state_max_bytes", STATE_MAX_BYTES)
    if os.path.isfile(state) and os.path.getsize(state) > limit:
        r.add("warning", "OSR-061", "state file is %d KB (> %d KB): every session pays it on every turn — move old "
              "milestones to history" % (os.path.getsize(state) // 1024, limit // 1024), ws["state_file"])
    d = ws.get("dir")
    cp = m.get("control_plane") or {}
    hist = cp.get("historical") or []
    if d and os.path.isdir(os.path.join(root, d)):
        known = set(ws.get("current") or []) | set(ws.get("templates") or [])
        for name in sorted(os.listdir(os.path.join(root, d))):
            relp = d + "/" + name + ("/" if os.path.isdir(os.path.join(root, d, name)) else "")
            if name in known or name.rstrip("/") in known or match_any(relp.rstrip("/"), hist) or match_any(relp, hist):
                continue
            r.add("warning", "OSR-060", "workspace item is neither current, template nor historical — reads as live state",
                  relp)
    banner = cp.get("historical_banner")
    if banner:
        for pat in hist:
            if pat.endswith("/"):
                continue
            for f in sorted(glob.glob(os.path.join(root, pat))):
                head = "\n".join((read_text(f) or "").split("\n")[:12])
                if not re.search(banner, head):
                    r.add("warning", "OSR-060", "historical file has no historical banner in its head", rel(root, f),
                          basis="declared")


def _generated(r, root, m, version):
    lock = load_json(os.path.join(root, LOCK)) or {}
    arts = lock.get("artifacts") or {}
    overrides = set(m.get("overrides") or [])
    for key, a in sorted(arts.items()):
        p = a.get("path")
        if a.get("kind") == "managed-keys" or not p:
            continue
        full = read_text(os.path.join(root, p))
        disk = render.extract_block(full or "") if a["kind"] == "block" else full
        if disk is None:
            r.add("warning", "OSR-070", "generated artifact missing (run oser update)", p)
            continue
        if p in overrides or a.get("overridden"):
            r.add("info", "OSR-070", "PROJECT-OVERRIDE: generated artifact kept by the project", p)
            continue
        if a.get("sha256") and sha(disk) != a["sha256"]:
            r.add("warning", "OSR-070", "generated artifact edited by hand since last update", p)
        if "NNC-OSER:GENERATED" not in disk[:600] and "NNC-OSER:BEGIN" not in disk[:300]:
            r.add("warning", "OSR-070", "generated artifact carries no provenance header", p)
    # would the running plugin generate something different?
    if not arts:
        return
    try:
        from .engine import update
        plan = update(root, dry_run=True, _skip_legacy_check=True)
        pending = [a for a in plan.actions if a[1] != LOCK]
        if arts and pending:
            r.add("warning", "OSR-070", "stale generated files: `oser update` would change %s"
                  % ", ".join(sorted(set(a[1] for a in pending))), None)
    except Exception as e:  # doctor must never crash on a broken tree
        r.add("warning", "OSR-070", "could not simulate update: %s" % e, None)


def _firebase(r, root, m):
    fb = get(m, "checks.firebase")
    if not fb:
        return
    rc = load_json(os.path.join(root, fb.get("rc", ".firebaserc"))) or {}
    cfg = load_json(os.path.join(root, fb.get("config", "firebase.json"))) or {}
    default = (rc.get("projects") or {}).get("default")
    data = fb.get("data_project")
    r.facts["firebase"] = {"default": default or "(none)", "aliases": rc.get("projects") or {}, "data_project": data}
    if default and default in (fb.get("forbidden_defaults") or []):
        r.add("critical", "OSR-080", ".firebaserc default is %r — a bare firebase command silently targets a forbidden project"
              % default, ".firebaserc", basis="declared")
    elif default and "firestore" in cfg and default != data:
        r.add("critical", "OSR-080", "default %r != data project %r while firebase.json declares firestore — "
              "a bare `firebase deploy` pushes rules/indexes to the wrong project" % (default, data), ".firebaserc", basis="declared")
    elif not default:
        r.add("info", "OSR-080", "no default Firebase project: every firebase command must name --project", ".firebaserc")
    hosting = cfg.get("hosting")
    for h in (hosting if isinstance(hosting, list) else [hosting] if hosting else []):
        site = h.get("site")
        if site and site in (fb.get("protected_sites") or []):
            r.add("critical", "OSR-080", "firebase.json hosting site %r is protected (owned elsewhere)" % site,
                  "firebase.json", basis="declared")
        elif site and site not in (fb.get("hosting_sites") or {}):
            r.add("warning", "OSR-080", "hosting site %r has no declared owning project" % site, "firebase.json", basis="declared")
    hits = []
    for pat in fb.get("admin_script_globs") or []:
        for f in sorted(glob.glob(os.path.join(root, pat))):
            text = read_text(f) or ""
            for bad in fb.get("forbidden_defaults") or []:
                if ('"%s"' % bad) in text or ("'%s'" % bad) in text:
                    hits.append(rel(root, f))
    if hits:
        r.add("warning", "OSR-080", "admin scripts hard-code forbidden project %s as a fallback label (guarded by "
              "--project=, verify before use): %s" % ("/".join(fb.get("forbidden_defaults")), ", ".join(sorted(set(hits)))),
              None, basis="declared")


def _plugin(r, root, version):
    ip = load_json(os.path.join(claude_home(), "plugins", "installed_plugins.json")) or {}
    table = ip.get("plugins", ip) if isinstance(ip, dict) else {}
    installed = {k: v for k, v in table.items() if isinstance(k, str) and k.startswith("nnc@")}
    vers = sorted({e.get("version") for entries in installed.values() for e in (entries if isinstance(entries, list) else [entries])
                   if isinstance(e, dict) and e.get("version")})
    r.facts["plugin_installed"] = ("%s %s" % (", ".join(sorted(installed)), "/".join(vers))) if installed else "(no)"
    r.facts["running_from"] = "plugin cache" if os.sep + "cache" + os.sep in OSER_HOME else "checkout " + OSER_HOME
    if not installed:
        r.add("info", "OSR-090", "nnc plugin not installed in Claude on this machine — OSER is running from %s" % OSER_HOME)
    elif vers and version not in vers:
        r.add("warning", "OSR-090", "installed nnc plugin %s differs from running OSER %s — `oser` on PATH and project "
              "wrappers resolve to the installed copy (update it: /plugin update nnc)" % ("/".join(vers), version))


def _git(r, root, main):
    if git(root, "rev-parse", "--git-dir")[0] != 0:
        return
    dirty = [l for l in git(root, "status", "--porcelain")[1].split("\n") if l.strip()]
    r.facts["git_dirty"] = len(dirty)
    if dirty:
        r.add("info", "OSR-095", "%d uncommitted path(s)" % len(dirty))
    rc, out = git(root, "rev-list", "--left-right", "--count", "HEAD...@{u}")
    if rc == 0 and out and out.split() != ["0", "0"]:
        r.add("warning", "OSR-095", "HEAD vs upstream ahead/behind = %s" % "/".join(out.split()))
    rc, out = git(root, "branch", "-r", "--merged", main, "--format=%(refname:short)")
    merged = [b for b in out.split("\n") if b and not b.endswith("/HEAD") and b.split("/", 1)[-1] != main and "/" in b]
    if merged:
        r.add("warning", "OSR-095", "%d remote branch(es) fully reachable from %s — prune candidates" % (len(merged), main))


# ------------------------------------------------------------------------------------------- output

def print_report(r):
    f = r.facts
    print("NNC OSER doctor %s — %s" % (f["oser_version"], f["project"]))
    print("  mode=%s  phase=%s  lock=%s  running-from=%s" % (f.get("mode", "?"), f.get("phase", "?"),
                                                          f.get("lock_version", "(none)"), f.get("running_from", "?")))
    if "authority" in f:
        print("  authority: %s%s" % (f["authority"], ("  [local: %s]" % f["authority_local"]) if f.get("authority_local") else ""))
    rm = f.get("root_model") or {}
    print("  ROOT model  EXPECTED=%s  CONFIGURED=%s  OBSERVED=%s" % (rm.get("expected"), rm.get("configured"), rm.get("observed")))
    if "firebase" in f:
        print("  firebase: default=%s data=%s" % (f["firebase"]["default"], f["firebase"]["data_project"]))
    print("  plugin installed: %s" % (f.get("plugin_installed"),))
    for x in r.findings:
        print("  [%-8s] %s %s%s%s" % (x["severity"].upper(), x["id"], ("(%s) " % x["path"]) if x["path"] else "",
                                     x["message"], "  {declared}" if x["basis"] == "declared" else ""))
    c = r.counts()
    print("SUMMARY critical=%d warning=%d info=%d" % (c["critical"], c["warning"], c["info"]))
    return 2 if c["critical"] else 1 if c["warning"] else 0
